### ISSUE TITLE
Unable to locate scores.pt, where to find this file ?

### ISSUE THREAD

**Issue by kd1729** [PeterQiu0516/Click-BERT#1]
![image](https://user-images.githubusercontent.com/55577276/149612155-6d3926f0-7c87-4e67-a9e7-cd09415c57e4.png)

**Comment by PeterQiu0516** [comment]
Hi @onlykingKD, thank you for your question. 

`scores.pt` are generated from this line of code. It simply stores the ground truth label of the Webis 17 dataset.
![image](https://user-images.githubusercontent.com/47267715/149612518-b1ffcdbf-1bb9-4ff6-ab83-ce32f96f1288.png)

**Comment by kd1729** [comment]
> Hi @onlykingKD, thank you for your question.
> 
> `scores.pt` are generated from this line of code. It simply stores the ground truth label of the Webis 17 dataset. ![image](https://user-images.githubusercontent.com/47267715/149612518-b1ffcdbf-1bb9-4ff6-ab83-ce32f96f1288.png)

Only these files are generated, no scores.pt file is being generated ?

![image](https://user-images.githubusercontent.com/55577276/149613015-d6988daf-0ca9-4db7-824b-dda6954479a2.png)

**Comment by PeterQiu0516** [comment]
Yes, and as I pointed out that `scores.pt` store the `score_all` matrix. So you can always generate a `scores.pt` file with that matrix.

**Comment by kd1729** [comment]
> Yes, and as I pointed out that `scores.pt` store the `score_all` matrix. So you can always generate a `scores.pt` file with that matrix.

ohhk understood, thank you :-)

**Comment by PeterQiu0516** [comment]
You are welcome :-)
